title: "Tyreek Haynes - Security Research"
description: "Vulnerability research, case studies, and security analysis"
baseurl: ""
url: url: "https://TyreekHaynes.github.io/Security-Research"

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - METHODOLOGY.md
